#spring:
#  application:
#    name: microservice-one
#server:
#  servlet:
#    context-path: /service-one
#  port: 8661
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: ${COMPUTERNAME}  



spring:
  application:
    name: um
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres 
    password: postgres 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /um
  port: 8661
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${COMPUTERNAME}  