server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${COMPUTERNAME} 
 
spring:
  cloud:
    gateway:
      routes:
        - id: um
          uri: lb://um
          predicates:
            - Path=/um/**
        - id: kyc
          uri: lb://kyc
          predicates:
            - Path=/kyc/**
        - id: rpt
          uri: lb://rpt
          predicates:
            - Path=/rpt/**
        - id: store
          uri: lb://store
          predicates:
            - Path=/store/**
#        - id: serviceThree
#          uri: lb://MICROSERVICE-THREE
#          predicates:
#            - Path=/service-three/**


